/**
 * Created by smorley on 2016-08-16.
 */
var pl = {
    "paymentOptions":[
        {Value: "PayPal", Label: "PayPal"},
        {Value: "Check", Label: "Check"},
    ],
    "statesList": [
        {Value: "AL", Label: "Alabama"},
        {Value: "AK", Label: "Alaska"},
        {Value: "AZ", Label: "Arizona"},
        {Value: "AR", Label: "Arkansas"},
        {Value: "CA", Label: "California"},
        {Value: "CO", Label: "Colorado"},
        {Value: "CT", Label: "Connecticut"},
        {Value: "DE", Label: "Delaware"},
        {Value: "FL", Label: "Florida"},
        {Value: "GA", Label: "Georgia"},
        {Value: "HI", Label: "Hawaii"},
        {Value: "ID", Label: "Idaho"},
        {Value: "IL", Label: "Illinois"},
        {Value: "IN", Label: "Indiana"},
        {Value: "IA", Label: "Iowa"},
        {Value: "KS", Label: "Kansas"},
        {Value: "KY", Label: "Kentucky"},
        {Value: "LA", Label: "Louisiana"},
        {Value: "ME", Label: "Maine"},
        {Value: "MD", Label: "Maryland"},
        {Value: "MA", Label: "Massachusetts"},
        {Value: "MI", Label: "Michigan"},
        {Value: "MN", Label: "Minnesota"},
        {Value: "MS", Label: "Mississippi"},
        {Value: "MO", Label: "Missouri"},
        {Value: "MT", Label: "Montana"},
        {Value: "NE", Label: "Nebraska"},
        {Value: "NV", Label: "Nevada"},
        {Value: "NH", Label: "New Hampshire"},
        {Value: "NJ", Label: "New Jersey"},
        {Value: "NM", Label: "New Mexico"},
        {Value: "NY", Label: "New York"},
        {Value: "NC", Label: "North Carolina"},
        {Value: "ND", Label: "North Dakota"},
        {Value: "OH", Label: "Ohio"},
        {Value: "OK", Label: "Oklahoma"},
        {Value: "OR", Label: "Oregon"},
        {Value: "PA", Label: "Pennsylvania"},
        {Value: "RI", Label: "Rhode Island"},
        {Value: "SC", Label: "South Carolina"},
        {Value: "SD", Label: "South Dakota"},
        {Value: "TN", Label: "Tennessee"},
        {Value: "TX", Label: "Texas"},
        {Value: "UT", Label: "Utah"},
        {Value: "VT", Label: "Vermont"},
        {Value: "VA", Label: "Virginia"},
        {Value: "WA", Label: "Washington"},
        {Value: "WV", Label: "West Virginia"},
        {Value: "WI", Label: "Wisconsin"},
        {Value: "WY", Label: "Wyoming"},
    ],
};
